// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djzfjjwebvylbwdpyjwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqemZqandlYnZ5bGJ3ZHB5andtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjIxNDAsImV4cCI6MjA2MTE5ODE0MH0.ofDhpusxjbc6f-22NjRZQ-kLlzrIJmI95WdStC7j75c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);